name: Build

on:
  push:
    branches:
      - development
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - development
  # Allow manual dispatch in GH
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - name: Install NPM dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
      - name: Lint
        run: pnpm lint
      # Create recursively the destination dir with
      # "--parrents where no error if existing, make parent directories as needed."
      - run: mkdir -p ./build/${{ github.head_ref || github.ref_name }}
      - name: Deploy to GitHub Pages
        if: github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # in stremio, we use `feat/features-name` or `fix/this-bug`
          # so we need a recursive creation of the destination dir
          destination_dir: ${{ github.head_ref || github.ref_name }}
          allow_empty_commit: true
